/* eslint-disable */
module.exports = {
  Theme: require('../src/components/Theme').default,
  ButtonForm: require('../src/components/ButtonForm').default,
  ButtonNav: require('../src/components/ButtonNav').default,
  ButtonProgram: require('../src/components/ButtonProgram').default,
  StartButton: require('../src/components/ButtonStart').default,
  ButtonIconLarge: require('../src/components/ButtonIconLarge').default,
  ButtonIconSmall: require('../src/components/ButtonIconSmall').default,
  StandardMenu: require('../src/components/StandardMenu').default,
  ExplorerIcon: require('../src/components/IconExplorerIcon').default,
  ListIcon: require('../src/components/IconListIcon').default,
  ExplorerView: require('../src/components/ExplorerView').default,
  Checkbox: require('../src/components/FormCheckbox').default,
  Radio: require('../src/components/FormRadio').default,
  InputText: require('../src/components/FormInputText').default,
  Select: require('../src/components/FormSelect').default,
  FakeSelect: require('../src/components/FormFakeSelect').default,
  SelectBox: require('../src/components/FormSelectBox').default,
  SelectBoxSimple: require('../src/components/FormSelectBoxSimple').default,
  StartMenu: require('../src/components/StartMenu').default,
  TaskBar: require('../src/components/TaskBar').default,
  Window: require('../src/components/Window').default,
  WindowAlert: require('../src/components/WindowAlert').default,
  WindowExplorer: require('../src/components/WindowExplorer').default,
  WindowProgram: require('../src/components/WindowProgram').default,
  DetailsSection: require('../src/components/DetailsSection').default,
};
